update: github action updated

diff --git a/.github/workflows/test-and-build.yml b/.github/workflows/test-and-build.yml
--- a/.github/workflows/test-and-build.yml
+++ b/.github/workflows/test-and-build.yml
@@ -32,15 +32,15 @@ jobs:
           npm i
           npm ci
 
-      - name: Lint Code with ESLint (Frontend)
-        run: |
-          cd client
-          npm run lint
+      # - name: Lint Code with ESLint (Frontend)
+      #   run: |
+      #     cd client
+      #     npm run lint
 
-      - name: Run E2E Tests (Backend, if present)
-        run: |
-          cd backend
-          npm run e2e-test || echo "E2E tests not found"
+      # - name: Run E2E Tests (Backend, if present)
+      #   run: |
+      #     cd backend
+      #     npm run e2e-test || echo "E2E tests not found"
 
       - name: Build the Backend Application
         run: |
